### ISSUE TITLE
Fatal error - yaml: control characters are not allowed

### ISSUE THREAD

**Issue by suntong** [go-easygen/easygen#6] opened 2017-06-03 20:49 UTC
@grrtrr I need to reverse the order for picking up yaml files --

When there are both `.yaml` file and another without `.yaml` extension, `easygen` now default to pick the one without `.yaml` extension. This will adversely affect my current usage, when I have both `pkg.yaml` file and `pkg` file in the directory, the latter being the built executable, causing the error 

`Fatal error - yaml: control characters are not allowed
`

Reversing the order for picking up yaml files so that `.yaml` file being picked with higher priority than the one without `.yaml` extension, it will not affect you, right? 

Just want to confirm with you before moving forward. Thx.

**Comment by grrtrr** [comment] 2017-06-04 01:08
@suntong - thanks for the heads-up and yes that is a problem; the current heuristic is not smart enough to avoid this.

Just checked in the code - the preference seems to come from `easygen.go:Generate()`. I imagine that it might be easier to move the test from there into the `range` loop of  `cmd/main.go`.

Are you working on this already, or would you like me to fix it in some way?

**Comment by suntong** [comment] 2017-06-04 02:35
I haven't looked into it, and will not be able to do that until Tuesday evening. Since you've looked into it already, I believe that you can find a good fix. So go ahead if you have some time, or I can look into it next Tuesday.

**Comment by suntong** [comment] 2017-06-04 02:39
Oh, sorry I forgot I have arrangement for next Tuesday evening as well. So the earliest I can look into it is next Wednesday.

**Comment by grrtrr** [comment] 2017-06-04 03:22
I just went over this - as far as I can see, the problem is not related to using files with or without `.yaml` extension.

I first verified this by experimentation - the following combinations all work:
```bash
> easygen -tf enum_java site_op       site_op.yaml message_type.yaml guest_type.yaml
> easygen -tf enum_java site_op       site_op.yaml message_type      guest_type.yaml
> easygen -tf enum_java site_op       site_op      message_type.yaml guest_type.yaml
> easygen -tf enum_java.tmpl site_op  site_op      message_type      guest_type.yaml
```

I then went over the code again -- what I said above was _wrong_:
- the test whether an input file has `.yaml` extension or not is done per each individual file,
- hence a file at position `n` is independent from a file at another position,
- so that `.yaml` and not-`.yaml` files can be freely mixed on the command-line.

The error message you show above may have to do with the `.yaml` itself -- could you check if the input file might have an issue with either the syntax, or the character set?

**Comment by suntong** [comment] 2017-06-04 03:53
The error was that easygen picked my `picv` instead of my `picv.yaml`, when I run `go generate -x` from https://github.com/suntong/picv, after first build. 

Of course, the `picv`, being the compiled executable, have all kinds of control characters.

**Comment by grrtrr** [comment] 2017-06-04 20:55
Oh I see ... :ok_hand: :
Fix is on the way.

**Closed** 2017-06-04 22:11 UTC
